# Generated by Django 2.2.1 on 2019-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(help_text='Enter city name', max_length=50)),
                ('desc', models.CharField(help_text='Enter Description', max_length=500)),
                ('price', models.IntegerField(help_text='Enter Booking Price')),
                ('img', models.FileField(help_text='add url of image', upload_to='')),
                ('show', models.BooleanField(help_text='Enter 0 if post is private')),
            ],
        ),
    ]
